name: Build Portable EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pyperclip

      - name: Download UPX (compressor)
        run: |
          curl -L https://github.com/upx/upx/releases/download/v4.2.4/upx-4.2.4-win64.zip -o upx.zip
          tar -xf upx.zip
          mkdir upx_dir
          move upx-4.2.4-win64\upx.exe upx_dir\upx.exe

      - name: Build EXE
        run: |
          pyinstaller --onefile --noconsole --clean --strip --upx-dir=upx_dir linga_offline_fixed.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Linga-Portable
          path: dist/*.exe
