    - name: Build EXE with PyInstaller (CMD shell)
      shell: cmd
      run: |
        pyinstaller linga_offline_fixed.py ^
          --onefile ^
          --noconsole ^
          --clean ^
          --strip ^
          --collect-all tk ^
          --collect-all tcl ^
          --add-binary "$(python -c "import sys,os;print(os.path.join(os.path.dirname(sys.executable),'python311.dll'))");."
