name: Build Portable EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd  # اجرای همه دستورات در cmd.exe تا مشکل escape برطرف شه

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install PyInstaller
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build EXE with PyInstaller
      run: >
        pyinstaller linga_offline_fixed.py --name LingaPortable
        --onefile --noconsole --clean --strip
        --collect-all tk --collect-all tcl
        --add-binary "%PythonLocation%\\python311.dll;."

    - name: Download and use UPX to compress EXE
      run: |
        curl -L https://github.com/upx/upx/releases/download/v4.2.3/upx-4.2.3-win64.zip -o upx.zip
        tar -xf upx.zip
        .\upx-4.2.3-win64\upx --best --lzma dist\LingaPortable.exe

    - name: Upload EXE artifact
      uses: actions/upload-artifact@v4
      with:
        name: Linga-Portable
        path: dist/LingaPortable.exe
